In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.externals import joblib

In [5]:
df=pd.read_csv('housing.csv')
df.head(5)

square_fit  price
0        1300  22000
1        2000  33000
2         800  11000
3         650   8500
4        2400  38000

In [10]:
model=linear_model.LinearRegression()
model.fit(df[['square_fit']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
model.coef_

array([16.74335179])

In [20]:
model.predict([[1100]])

array([17334.51610388])

In [22]:
#now i save my model to joblib
joblib.dump(model,'housing_prediction_saved_model')

['housing_prediction_saved_model']

In [23]:
saved_model=joblib.load('housing_prediction_saved_model')

In [25]:
saved_model.predict([[1100]])

array([17334.51610388])